apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image-mglg4
  namespace: kabanero
spec:
  type: image
  params:
    - name: url
      value: docker.io/yellocabins/demo-with-andrew:latest
