apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: my-pipeline-resource-image
  namespace: kabanero
spec:
  type: image
  params:
    - name: url
      value: gcr.io/staging-images/kritis
